import { NextResponse } from 'next/server';
import { seedAgentsIfEmpty } from '@/lib/mongodb/agents';
import { seedListingsIfEmpty } from '@/lib/mongodb/listings';
import { seedGraphicsIfEmpty } from '@/lib/mongodb/graphics';
import { seedPackagesIfEmpty } from '@/lib/mongodb/packages';
import { greg, testAgent, demoAgent } from '@/lib/theme';
import type { Listing, Graphic, Package } from '@/lib/types';

const INITIAL_PACKAGES: Package[] = [
  {
    _id: 'pkg-8',
    agentId: 'greg-caseley',
    type: '8-pack',
    purchasedAt: '2026-04-15',
    status: 'completed',
  },
  {
    _id: 'pkg-16',
    agentId: 'greg-caseley',
    type: '16-pack',
    purchasedAt: '2026-08-04',
    status: 'active',
  },
  {
    _id: 'pkg-rm-8',
    agentId: 'demo-agent',
    type: '8-pack',
    purchasedAt: '2026-09-08',
    status: 'active',
  },
];

const INITIAL_LISTINGS: Listing[] = [
  {
    _id: 'listing-8pack-sold',
    agentId: 'greg-caseley',
    address: 'Sold Property',
    city: 'Charlottetown',
    province: 'PE',
    mls: '202604-01',
    price: null,
    propertyType: 'residential',
    photos: [],
    status: 'delivered',
    submittedAt: '2026-04-28',
    deliveredAt: '2026-04-30',
    requestedVariants: ['just-sold'],
    createdAt: new Date('2026-04-28'),
    updatedAt: new Date('2026-04-30'),
  },
  {
    _id: 'listing-8pack-generic',
    agentId: 'greg-caseley',
    address: 'Greg Caseley Promo',
    city: 'Charlottetown',
    province: 'PE',
    mls: '202605-01',
    price: null,
    propertyType: 'residential',
    photos: [],
    status: 'delivered',
    submittedAt: '2026-05-01',
    deliveredAt: '2026-05-02',
    requestedVariants: ['featured'],
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date('2026-05-02'),
  },
  {
    _id: 'listing-8pack-lot',
    agentId: 'greg-caseley',
    address: 'Lot for Sale',
    city: 'Cornwall',
    province: 'PE',
    mls: '202605-02',
    price: 65000,
    propertyType: 'land',
    acres: 1.5,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-05-12',
    deliveredAt: '2026-05-13',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-05-12'),
    updatedAt: new Date('2026-05-13'),
  },
  {
    _id: 'listing-8pack-riverbend',
    agentId: 'greg-caseley',
    address: 'A19 Riverbend Lane',
    city: 'Cornwall',
    province: 'PE',
    mls: '202606-01',
    price: 95000,
    propertyType: 'land',
    acres: 1.2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-06-08',
    deliveredAt: '2026-06-09',
    requestedVariants: ['price-drop'],
    createdAt: new Date('2026-06-08'),
    updatedAt: new Date('2026-06-09'),
  },
  {
    _id: 'listing-8pack-laura',
    agentId: 'greg-caseley',
    address: '2 Laura Lane',
    city: 'Cornwall',
    province: 'PE',
    mls: '202607-01',
    price: 489000,
    propertyType: 'residential',
    beds: 3,
    baths: 2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-07-01',
    deliveredAt: '2026-07-29',
    requestedVariants: ['open-house', 'price-drop'],
    createdAt: new Date('2026-07-01'),
    updatedAt: new Date('2026-07-29'),
  },
  {
    _id: 'listing-new-orleans',
    agentId: 'greg-caseley',
    address: '1104 New Orleans Rd',
    city: 'Charlottetown',
    province: 'PE',
    mls: '202608-01',
    price: 389000,
    propertyType: 'residential',
    beds: 3,
    baths: 2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-04',
    deliveredAt: '2026-08-04',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-08-04'),
    updatedAt: new Date('2026-08-04'),
  },
  {
    _id: 'listing-thompson',
    agentId: 'greg-caseley',
    address: '11 Thompson Road',
    city: 'Stratford',
    province: 'PE',
    mls: '202608-02',
    price: 449000,
    propertyType: 'residential',
    beds: 4,
    baths: 2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-10',
    deliveredAt: '2026-08-10',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-10'),
  },
  {
    _id: 'listing-morrison',
    agentId: 'greg-caseley',
    address: '71 Morrison Lane',
    city: 'Cornwall',
    province: 'PE',
    mls: '202608-03',
    price: 525000,
    propertyType: 'residential',
    beds: 4,
    baths: 3,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-16',
    deliveredAt: '2026-08-25',
    requestedVariants: ['open-house', 'price-drop'],
    createdAt: new Date('2026-08-16'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'listing-laura-lane',
    agentId: 'greg-caseley',
    address: '2 Laura Lane',
    city: 'Cornwall',
    province: 'PE',
    mls: '202608-04',
    price: 475000,
    propertyType: 'residential',
    beds: 3,
    baths: 2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-23',
    deliveredAt: '2026-08-25',
    requestedVariants: ['open-house'],
    createdAt: new Date('2026-08-23'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'listing-riverbend',
    agentId: 'greg-caseley',
    address: 'A19 Riverbend Lane',
    city: 'Cornwall',
    province: 'PE',
    mls: '202608-05',
    price: 89000,
    propertyType: 'land',
    acres: 1.2,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-25',
    deliveredAt: '2026-08-25',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-08-25'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'listing-salt-wind',
    agentId: 'greg-caseley',
    address: 'Lot 1 & 2 Salt Wind Way',
    city: 'North Rustico',
    province: 'PE',
    mls: '202608-06',
    price: 125000,
    propertyType: 'land',
    acres: 2.5,
    photos: [],
    status: 'delivered',
    submittedAt: '2026-08-30',
    deliveredAt: '2026-09-09',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-08-30'),
    updatedAt: new Date('2026-09-09'),
  },
  {
    _id: 'listing-rm-seaside',
    agentId: 'demo-agent',
    address: '156 Seaside Lane',
    city: 'Summerside',
    province: 'PE',
    mls: '202609-01',
    price: 425000,
    propertyType: 'residential',
    beds: 4,
    baths: 2,
    photos: [],
    status: 'pending',
    submittedAt: '2026-09-08',
    requestedVariants: ['new-listing', 'open-house'],
    createdAt: new Date('2026-09-08'),
    updatedAt: new Date('2026-09-08'),
  },
  {
    _id: 'listing-rm-harbour',
    agentId: 'demo-agent',
    address: '3 Harbour View Drive',
    city: 'Charlottetown',
    province: 'PE',
    mls: '202609-02',
    price: 549000,
    propertyType: 'residential',
    beds: 3,
    baths: 2,
    photos: [],
    status: 'pending',
    submittedAt: '2026-09-09',
    requestedVariants: ['new-listing'],
    createdAt: new Date('2026-09-09'),
    updatedAt: new Date('2026-09-09'),
  },
  {
    _id: 'listing-rm-queens',
    agentId: 'demo-agent',
    address: '88 Queen Street',
    city: 'Charlottetown',
    province: 'PE',
    mls: '202609-03',
    price: 389000,
    propertyType: 'residential',
    beds: 2,
    baths: 1,
    photos: [],
    status: 'pending',
    submittedAt: '2026-09-10',
    requestedVariants: ['new-listing', 'price-drop'],
    createdAt: new Date('2026-09-10'),
    updatedAt: new Date('2026-09-10'),
  },
  {
    _id: 'listing-rm-waterfront',
    agentId: 'demo-agent',
    address: '22 Waterfront Crescent',
    city: 'Stratford',
    province: 'PE',
    mls: '202609-04',
    price: 675000,
    propertyType: 'residential',
    beds: 5,
    baths: 3,
    photos: [],
    status: 'in-progress',
    submittedAt: '2026-09-11',
    requestedVariants: ['new-listing', 'open-house', 'coming-soon'],
    createdAt: new Date('2026-09-11'),
    updatedAt: new Date('2026-09-11'),
  },
];

const INITIAL_GRAPHICS: Graphic[] = [
  {
    _id: 'g-8pack-sold',
    listingId: 'listing-8pack-sold',
    templateId: 'style-b-square',
    variant: 'just-sold',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/sold and closed.png',
    createdAt: new Date('2026-04-30'),
    updatedAt: new Date('2026-04-30'),
  },
  {
    _id: 'g-8pack-promo',
    listingId: 'listing-8pack-generic',
    templateId: 'style-b-square',
    variant: 'featured',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/greg-graphic.png',
    createdAt: new Date('2026-05-02'),
    updatedAt: new Date('2026-05-02'),
  },
  {
    _id: 'g-8pack-lot',
    listingId: 'listing-8pack-lot',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/graphic.png',
    createdAt: new Date('2026-05-13'),
    updatedAt: new Date('2026-05-13'),
  },
  {
    _id: 'g-8pack-riverbend',
    listingId: 'listing-8pack-riverbend',
    templateId: 'style-b-square',
    variant: 'price-drop',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/new-price.png',
    createdAt: new Date('2026-06-09'),
    updatedAt: new Date('2026-06-09'),
  },
  {
    _id: 'g-8pack-laura-1',
    listingId: 'listing-8pack-laura',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/laura-lane-open-house.png',
    createdAt: new Date('2026-07-18'),
    updatedAt: new Date('2026-07-18'),
  },
  {
    _id: 'g-8pack-laura-2',
    listingId: 'listing-8pack-laura',
    templateId: 'style-b-square',
    variant: 'price-drop',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/laura-lane-price-adjust.png',
    createdAt: new Date('2026-07-22'),
    updatedAt: new Date('2026-07-22'),
  },
  {
    _id: 'g-8pack-laura-3',
    listingId: 'listing-8pack-laura',
    templateId: 'style-b-square',
    variant: 'price-drop',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-8',
    historyUrl: '/history/greg-8pack/laura-lane-price-improvement.png',
    createdAt: new Date('2026-07-29'),
    updatedAt: new Date('2026-07-29'),
  },
  {
    _id: 'g-new-orleans-1',
    listingId: 'listing-new-orleans',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/new-orleans-road.png',
    createdAt: new Date('2026-08-04'),
    updatedAt: new Date('2026-08-04'),
  },
  {
    _id: 'g-thompson-1',
    listingId: 'listing-thompson',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/11-thompson-road.png',
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-10'),
  },
  {
    _id: 'g-morrison-1',
    listingId: 'listing-morrison',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: { date: 'August 22', time: '2:00 - 4:00 PM' },
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/thompson-point-open-house-aug-22.png',
    createdAt: new Date('2026-08-16'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    _id: 'g-morrison-2',
    listingId: 'listing-morrison',
    templateId: 'style-b-square',
    variant: 'price-drop',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/morrison-lane-improvement.png',
    createdAt: new Date('2026-08-20'),
    updatedAt: new Date('2026-08-20'),
  },
  {
    _id: 'g-morrison-3',
    listingId: 'listing-morrison',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: { date: 'August 23' },
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/morrison-lane-open-house.png',
    createdAt: new Date('2026-08-23'),
    updatedAt: new Date('2026-08-23'),
  },
  {
    _id: 'g-morrison-4',
    listingId: 'listing-morrison',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: { date: 'August 25' },
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/unnamed-agent-morrison-lane.png',
    createdAt: new Date('2026-08-25'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'g-laura-1',
    listingId: 'listing-laura-lane',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: { date: 'August 30', time: '1:00 - 3:00 PM' },
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/laura-lane-open-house-aug-30.png',
    createdAt: new Date('2026-08-23'),
    updatedAt: new Date('2026-08-23'),
  },
  {
    _id: 'g-laura-2',
    listingId: 'listing-laura-lane',
    templateId: 'style-b-square',
    variant: 'open-house',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/leah-sadicon.png',
    createdAt: new Date('2026-08-25'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'g-riverbend-1',
    listingId: 'listing-riverbend',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/a19-riverbend.png',
    createdAt: new Date('2026-08-25'),
    updatedAt: new Date('2026-08-25'),
  },
  {
    _id: 'g-saltwind-1',
    listingId: 'listing-salt-wind',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/salt-wind-way-lot-1.png',
    createdAt: new Date('2026-08-30'),
    updatedAt: new Date('2026-08-30'),
  },
  {
    _id: 'g-saltwind-2',
    listingId: 'listing-salt-wind',
    templateId: 'style-b-square',
    variant: 'new-listing',
    overrides: {},
    photoAssignments: {},
    packageId: 'pkg-16',
    historyUrl: '/history/greg-16pack/salt-wind-way-new-listing.png',
    createdAt: new Date('2026-09-09'),
    updatedAt: new Date('2026-09-09'),
  },
];

export async function POST() {
  try {
    await seedAgentsIfEmpty([greg, demoAgent, testAgent]);
    await seedPackagesIfEmpty(INITIAL_PACKAGES);
    await seedListingsIfEmpty(INITIAL_LISTINGS);
    await seedGraphicsIfEmpty(INITIAL_GRAPHICS);

    return NextResponse.json({ success: true, message: 'Database seeded if empty' });
  } catch (error) {
    console.error('[API] POST /api/seed error:', error);
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({ message: 'POST to this endpoint to seed the database' });
}
